### ISSUE TITLE
composer require failed

### ISSUE THREAD

**Issue by evxzibit** [cewi/excel#1]
Thanks for this plugin. I am trying to run composer require Cewi/Excel after  adding 
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cewi/excel"
        }
    ],
on my composer.json but i get the following error 
"[InvalidArgumentException] Could not find package Cewi/Excel at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability"

Please help

**Comment by evxzibit** [comment]
Never mind the above. I got this to work by running composer require Cewi/Excel dev-master

**Comment by cewi** [comment]
updated Readme.md
