### ISSUE TITLE
 PHPExcelHelper could not be found. 

### ISSUE THREAD

**Issue by KeidyU** [cewi/excel#10]
Hi guys,
I am trying to use this plugin, but the problem " PHPExcelHelper could not be found. "

In AppController
$this->loadComponent('RequestHandler',['viewClassMap' => ['xlsx' => 'Cewi/Excel.Excel']]);

In my Controller
public $helpers = ['Cewi/Excel.Excel'];

in my view:
$this->Excel->addWorksheet($matches, 'controllersStatus');

phpexcel is in:
vendor/phpoffice/phpexcel

i think this can be solved with
require_once(ROOT. DS .'vendor'.DS.'phpoffice/phpexcel/Classes');

but nothing happen i dont where to put the require_once sentence! some help will be amazing.
thanks

**Comment by cewi** [comment]
In cakephp, you've to use autoloading. No `require_once` needed.
Did you load the plugin? 
You have to add 
`Plugin::load('Cewi/Excel', ['bootstrap' => true, 'routes'=>true]);`
in your bootstrap.php file.

**Comment by KeidyU** [comment]
Yes this is my last line in bootstrap.php
Plugin::load('Cewi/Excel', ['bootstrap' => true, 'routes'=>true]);

I dont have problem when i use $this->loadComponent('Cewi/Excel.Import');

the problem is with public $helpers = ['Cewi/Excel.Excel']; when the helper call PHPExcel Helper.

No so much information i had check all the link in a google search. :(

**Comment by KeidyU** [comment]
Hi Cewi,
I am  trying something today. i followed this steps as you described
router.php
  Router::extensions(['xlsx']);

ArticlesController:
   public $helpers = ['Cewi/Excel.Excel'];

add a Folder 'xlsx' in Template/Articles and create the file 'index.ctp' in this Folder. 
    $this->Excel->addWorksheet($articles, 'Articles');
  
create the link to generate the file somewhere in your app: 
    <?= $this->Html->link(__('Excel'), ['controller' => 'Articles', 'action' => 'index', '_ext'=>'xlsx']); ?>

'_ext'  is working as index.xlsx

and of course i am getting the error 
Missing Method in ArticlesController   public function index.xlsx()

Some advice please

**Comment by KeidyU** [comment]
Can be something about this:

Deprecated since version 3.1.0: As of 3.1.0 the viewClassMap() method is deprecated. You should use config() to change the viewClassMap at runtime.
???

**Comment by KeidyU** [comment]
Got it guys,

in router.php the line 

Router::extensions(['xlsx']);

must be before the method Router::scope('/', function (RouteBuilder $routes) {}
Something like this:

router.php:

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::extensions(['xlsx']);

Router::defaultRouteClass(DashedRoute::class);
Router::scope('/', function (RouteBuilder $routes) 
{
   ..
   ..
}

**Comment by cewi** [comment]
that's true. If you want to use it inside a scope, you've to write `$routes->extensions(['xlsx']);` Will clear that in the doku.
Have fun!
