### ISSUE TITLE
Personalization of the file name

### ISSUE THREAD

**Issue by damiankosiorowski** [cewi/excel#19]
The 'response' overwrite is required to change the file name!

Now:
https://github.com/cewi/excel/blob/f289700dcee46fa88662783da28247992eef8a51/src/View/ExcelView.php#L106

Should:
`$this->setResponse($this->response->withDownload($this->getFilename()));`

**Comment by cewi** [comment]
not sure if I got you right? Anyway: If you want to change the name for the downloaded file, there is now a method in the helper. Just add 
```$this->Excel->setFilename('foo');``` 
to your template file. Download will now be named 'foo.xlsx'.
