### ISSUE TITLE
Cewi/Excel Deprecation

### ISSUE THREAD

**Issue by IamSaajidhBorham** [cewi/excel#20]
I have used the plugin in my cakephp app and I have put in my DigitalOcean server. So my server is running with PHP 7.2.19 and I couldn't find a solution why it affecting to run cake. 
The error I get,
"Deprecation warning: require.Cewi/Excel is invalid, it should not contain uppercase characters. Please use cewi/excel instead. Make sure you fix this as Composer 2.0 will error. Do not run Composer as root/super user! See https://getcomposer.orgroot for details."
Every time I try to update composer, this warning comes and tells Cewi/Excel plugin is deprecated.

Can you help me with this problem?

**Comment by cewi** [comment]
did you try it with "require cewi/excel"? I will check this later and adapt the documentation. HTH

**Comment by cewi** [comment]
to install the plugin simply use "composer require cewi/excel". I updated the readme.
