### ISSUE TITLE
Creating worksheets with Date objects

### ISSUE THREAD

**Issue by aa411853** [cewi/excel#3]
Any ideas for how to work around Date objects from CakePHP queries?

Error: Cannot use object of type Cake\I18n\Date as array
File /var/www/html/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell/DefaultValueBinder.php
Line: 90 

Sample data:

App\Model\Entity\Account Object
(
    [id] => 2
    [deal_id] => 56
    [contact_id] => 5273
    [cb_contact_id] => 5302
    [deal_type] => F
    [app_type] => I
    [status] => Active
    [location_id] => 2
    [stock_no] => CHE60856
    [contract_date] => Cake\I18n\Date Object
        (
            [time] => 2016-03-22T00:00:00+00:00
            [timezone] => UTC
            [fixedNowTime] => 
        )
)

**Comment by cewi** [comment]
Date handling changed recently in Cake3. Do you use 3.2?
I'll look on it ASAP

**Comment by aa411853** [comment]
Hello, yes I'm working with 3.2.6. Thanks in advance for any help you can provide!

**Comment by cewi** [comment]
The Helper checked only if a entity property was of type \Cake\i18n\Time. Added now the types  \Cake\i18n\Date, \Cake\i18n\FrozenTime and \Cake\i18n\FrozenDate. 
Does ist work for you, now?

**Comment by aa411853** [comment]
Yes, that seems to have fixed the issue.  Thanks for responding so quickly
