### ISSUE TITLE
Export current results

### ISSUE THREAD

**Issue by brhsasa** [cewi/excel#7]
No way of exporting current results, each time you click on export link, you pass through the action then retrieving data, then export to excel, but what if any one wants to export data after doing a search or filtering data then he/she wants to export that results? he/she can't because he will need to pass to the action some additional data to the query.

**Comment by beescalante** [comment]
Hi. Firstly, _I apologize for my bad English._
Yes, of course, he's right. I also need to know how you can export if there is a filtering.
I have not been able to import, I would like to know if you can help us with an example to do it since in the instructions I have not been able to understand.
Regards!

**Comment by brhsasa** [comment]
@beescalante The import is working, do you have an issue with it ?

**Comment by cewi** [comment]
Hi,
it is possible to export a filtered set of results, You first have to implement the filter logic to get your desired results. This is beyond of the scope of this plugin. You can use for example https://github.com/FriendsOfCake/search or do it on your own. Than export the found collection of results to a view and use the helper as described in the readme to my plugin.
HTH!

**Comment by brhsasa** [comment]
Hi, i have tried with a simple example, i have created a CakePHP Form like so:

`<?= $this->Form->create(null,['url' => ['controller' => 'MyController', 'action' => 'MyAction',  '_ext'=>'xlsx'], 'class' => 'form-inline', 'type' => 'get','id' => 'FormID']) ?>`
// input controls inside the Form
`<?= $this->Form->end() ?>`

Then I have tried to submit data using HTMLHelper:
 `<?= $this->Html->link(__('Excel'), [ ],['onclick' => '$('#FormID').submit();']); ?>`
But the HTML Link does not even acts as a submit button.
But if i try using 
`<a onclick="$('#FormID').submit();" class="btn btn-orange"  type="submit" > submit </a>` the submit works fine and URL looks like: 
`/myapp/mycontroller/myaction.xlsx?data1=....&data2=...`

**Comment by cewi** [comment]
So did it finally work for you?
Then please close the issue.

**Comment by brhsasa** [comment]
It worked but without using HTMLHelper but you have to fix that.
Also another issue in you code is that either I have added this code `$this->Excel->addWorksheet($articles, 'Articles');` or not inside xlsx/index.ctp file, the xlsx is beening generated any way, and thats an issue must be fixed as well, try to remove that code and you will get xlsx file, so if I added an if else for that code it won't work means something like this:

`if($articles->count() == 0){ 

   // do not generate xlsx file, and show a error flash message....
} else{
 $this->Excel->addWorksheet($articles, 'Articles');
}`

**Comment by cewi** [comment]
If you want to have a flash message in case of an empty result set, you have to check that in the controller before sending the results to the view, where the Excel-Helper is invoked.
```
if($articles->count() == 0){
    // do not generate xlsx file, and show a error flash message....
   $this->Flash->warning('No Articles found, will not create Excel file!');
   $this->redirect(['action'=>'other_action']);
} else{
   $this->set('articles,'$articles);
}
...
```
Furthermore, it's not always desirable to cancel the creating of the Excel file in case of an empty collection. One could want to send more the one worksheet to the resulting Excel file. It would be a bad idea to stop the whole process in case one of the worksheets would be empty.
For example think of an excel file with all e-mail addresses in your users table grouped by role. 
Then in users controller: 
````
$this->set('admins', $this->Users->find()->where(['role'=>'admin'])->select(['email]));
$this->set('editors', $this->Users->find()->where(['role'=>'editor'])->select(['email]));
$this->set('users', $this->Users->find()->where(['role'=>'user'])->select(['email]));
`````
and in the view:
````
$this->Excel->addWorksheet($admins, 'Admins');
$this->Excel->addWorksheet($editors, 'Editors');
$this->Excel->addWorksheet($users, 'Users');
`````

**Comment by brhsasa** [comment]
Hi, 
That is what i did before, i canceled sending data to the view, and as you said it is not a good idea if you have multiple worksheets, but you should stop the porcess otherwise an Exception will be thrown (call on null object).
But you should know that either i added this line or no `$this->Excel->addWorksheet($articles, 'Articles');` the excel file is being generated any way. 
another thing there is no way from your doc how you can customize excel header, the only way is to use aliases in query.

**Comment by beescalante** [comment]
@brhsasa Hi! 
I had not seen all the comments. 
I do not know how to apply the import. I sure can not understand the documentation!!

**Comment by cewi** [comment]
Here are the Steps you need to import data:
- You need a Excel-File with a worksheet with the data you want to import on your server(e.g. upload it to your TMP-directory). Every row must contain data for one entity/record. First row must contain the names of the entity's properties (database columns).
- load the import component and feed the excel file to the prepareEntityData - Method as decribed in the readme.
-  with the resulting array, you can build entities for saving them as ususal.

@beescalante 
If you need further help, you're welcome. Please open then a new issue, if you've problems with importing excel-files. This issue was on exporting data to excel-files.
