### ISSUE TITLE
Import Excel

### ISSUE THREAD

**Issue by beescalante** [cewi/excel#8]
Hi! 
I'm trying to import excel with the steps of README. This is what I did:

 **In my Entity Controller:**

> class ProductsController extends AppController
> {
>     public $helpers = ['Cewi/Excel.Excel'];
>     
> public function initialize()
>     {
>         parent::initialize();
>         $this->loadComponent('Cewi/Excel.Import');
>     }
>     public function importProducts() 
>     {
>         $table = TableRegistry::get('Products');
>         $data = $this->Import->prepareEntityData(TMP . $this->request->data['content']['tmp_name']);
>         $products = $table->newEntities($data);
>         foreach ($products as $product) {
>         $table->save($product, ['checkExisting' => false]);
>         }
> }

**In my view import_products.ctp**

> <?= $this->Form->create($product, ['type'=>'file']) ?>
> <?php echo $this->Form->input('content',['type'=>'file']); ?>
> <?= $this->Form->button(__('Import')) ?>
> <?= $this->Form->end() ?>
 
But I get these errors:

> file_get_contents failed to open stream: No such file or directory [ROOT\vendor\phpoffice\phpexcel\Classes\PHPExcel\Shared\OLERead.php, line 85]
> fopen failed to open stream: No such file or directory [ROOT\vendor\phpoffice\phpexcel\Classes\PHPExcel\Reader\Abstract.php, line 203]

 I don't know what lacked. What was wrong with my code?

Thanks for your help!

**Comment by cewi** [comment]
Maybe you omitted something but the code for the view doesn't seem to be correct. I think it should be like this:
````
echo $this->Form->create(null, ['type'=>'file']); 
echo $this->Form->file('content'); 
echo $this->Form->submit(__('Import'));
echo $this->Form->end(); 
`````
Then in your controller method, you've to check wether it is a post or a get request. But most important, you must really upload the file. Something like:
````
public function importProducts()
{
$table = TableRegistry::get('Products');
    if ($this->request->is('post')) {
       move_uploaded_file($this->request->data['content']['tmp_name'], TMP . $this->request->data['content']['name']);
       $data = $this->Import->prepareEntityData(TMP . $this->request->data['content']['name']);
       $products = $table->newEntities($data);
       foreach ($products as $product) {
            $table->save($product, ['checkExisting' => false]);
      }
    }
}
`````
You should also validate the file before feeding it to the component, to ensure its is of excel-type.
HTH
BTW: you don't need the Helper, when you're not exporting data.

**Comment by beescalante** [comment]
Thank you very much, it has been helpful! I do not leave the errors.
But, I do not know how to validate the file. Now it just does not happen to do "Import".
The file loads well into the TMP folder but does not go to the database, I can not imagine what I am missing now.

Sorry for specifically asking what I need. I'm new to cakephp and sometimes it's hard for me to understand how some things work.

**Comment by cewi** [comment]
For validating data from a 'modelless form', you should read: https://book.cakephp.org/3.0/en/core-libraries/form.html. The rule 'uploadedFile' would probably suite well: https://api.cakephp.org/3.4/class-Cake.Validation.Validation.html#_uploadedFile.

I would recommend to check the array, you get back from the import component. Simply insert a 
`````
dd($data); 
`````
directly after the line:
`````
$data = $this->Import->prepareEntityData(TMP . $this->request->data['content']['name']);
`````
Given you had 'property_1', 'property_2' and a 'property_3' in the first row and some values in rows 2 - 4 of the excel file, the resulting array should look like:
```
[
	(int) 0 => [
		'Property_1' => 'Value_1',
		'Property_2' => 'Value_2',
		'Property_3' => 'Value_3'
	],
	(int) 1 => [
		'Property_1' => 'Value_4',
		'Property_2' => 'Value_5',
		'Property_3' => 'Value_6'
	],
	(int) 2 => [
		'Property_1' => 'Value_7',
		'Property_2' => 'Value_8',
		'Property_3' => 'Value_9'
	]
]


```
If the array is ok, you can then build the entities. Maybe it's a good idea to control them, too. After removing the dd($data) from above, insert a:
`````
dd($entities);
``````
after the line:
``````
$entities = $table->newEntities($data);
``````
The objects should not contain an 'errors' property. Finally you can check what went wrong while saving. Simply check $entity->errors() after saving.
Read about validation errors here:
https://book.cakephp.org/3.0/en/orm/entities.html#validation-errors 

HTH

**Comment by beescalante** [comment]
Thank you very much! I managed to import thanks to your help.

The only thing is that importing when the record already exists does not detect it but generates new records with the same information.

In that case the "['checkExisting' => false]" is not good for that?

**Comment by cewi** [comment]
I think you're right. But at the moment I cannot check that. You should find the Information here:
https://book.cakephp.org/3.0/en/orm/saving-data.html

**Comment by beescalante** [comment]
Thank you very much for your help. For those who need this, this is what I did: 
I used the version 3.4 of Cakephp

**In my controller:**

```
use App\Controller\AppController;
use Cake\ORM\TableRegistry;
class TdiasController extends AppController
{
    public function initialize()
        {
            parent::initialize();
            
            $this->loadComponent('Cewi/Excel.Import');
        }

    public function importProducts() 
     {
       //bulk add to new records
        $table = TableRegistry::get('Products');
        if ($this->request->is('post')) {
            move_uploaded_file($this->request->data['content']['tmp_name'], TMP . $this->request->data['content']['name']);
       
            $data = $this->Import->prepareEntityData(TMP . $this->request->data['content']['name']);
            //dd($data);  to see data import
            $products = $table->newEntities($data);
            //dd($products); to see specify data import entity and validations
            foreach ($products as $product) {
                $table->save($product, ['checkExisting' => false]);
             }
         } 
}  
```

**Important:** the fields (in database) that receive the data must be FLOAT type, to import excel file.

**In my view:**

```
<?= $this->Form->create(null, ['type'=>'file']) ?>
<?php echo $this->Form->file('content'); ?>
<?= $this->Form->button(__('Import')) ?>
<?= $this->Form->end() ?>
```
    

I hope this can help others!!
